import type { PlanRecord } from "./types";

const now = new Date();

export const seedPlans: PlanRecord[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    slug: "saudi-1gb-7-days",
    title: "Saudi 1GB",
    subtitle: "Light data for short stays",
    country: "SA",
    dataAmountMb: 1024,
    validityDays: 7,
    network: "Zain / STC placeholder",
    description:
      "A small Saudi data eSIM for maps, messaging and light browsing during a short Umrah trip.",
    featureList: [
      "1GB mobile data",
      "7 days validity",
      "Data-only eSIM, no phone number",
      "Install before travel, activate on arrival",
    ],
    costPence: null,
    markupType: "none",
    markupValue: null,
    retailPricePence: null,
    providerRefs: {
      mock: "mock-sa-1gb-7d",
      airalo: "TODO_AIRALO_1GB_7D",
      maya: "TODO_MAYA_1GB_7D",
      esimaccess: "TODO_ESIMACCESS_1GB_7D",
    },
    badge: "PRICE TBD",
    active: true,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    slug: "saudi-5gb-15-days",
    title: "Saudi 5GB",
    subtitle: "Balanced Umrah plan",
    country: "SA",
    dataAmountMb: 5120,
    validityDays: 15,
    network: "Zain / STC placeholder",
    description:
      "A practical Saudi data eSIM for messaging, maps, browsing and staying reachable during a typical Umrah itinerary.",
    featureList: [
      "5GB mobile data",
      "15 days validity",
      "Useful for maps and family messaging",
      "Data-only eSIM, no phone number",
    ],
    costPence: null,
    markupType: "none",
    markupValue: null,
    retailPricePence: null,
    providerRefs: {
      mock: "mock-sa-5gb-15d",
      airalo: "TODO_AIRALO_5GB_15D",
      maya: "TODO_MAYA_5GB_15D",
      esimaccess: "TODO_ESIMACCESS_5GB_15D",
    },
    badge: "Most popular placeholder",
    active: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    slug: "saudi-10gb-30-days",
    title: "Saudi 10GB",
    subtitle: "Longer trips and heavier use",
    country: "SA",
    dataAmountMb: 10240,
    validityDays: 30,
    network: "Zain / STC placeholder",
    description:
      "A larger data allowance for pilgrims staying longer or using their phone more often while travelling between Makkah and Madinah.",
    featureList: [
      "10GB mobile data",
      "30 days validity",
      "Good for longer stays",
      "Data-only eSIM, no phone number",
    ],
    costPence: null,
    markupType: "none",
    markupValue: null,
    retailPricePence: null,
    providerRefs: {
      mock: "mock-sa-10gb-30d",
      airalo: "TODO_AIRALO_10GB_30D",
      maya: "TODO_MAYA_10GB_30D",
      esimaccess: "TODO_ESIMACCESS_10GB_30D",
    },
    badge: "PRICE TBD",
    active: true,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    slug: "saudi-20gb-30-days",
    title: "Saudi 20GB",
    subtitle: "For sharing, maps and frequent browsing",
    country: "SA",
    dataAmountMb: 20480,
    validityDays: 30,
    network: "Zain / STC placeholder",
    description:
      "A high-allowance Saudi data eSIM for pilgrims who expect frequent browsing, uploads and navigation.",
    featureList: [
      "20GB mobile data",
      "30 days validity",
      "Higher allowance for frequent use",
      "Data-only eSIM, no phone number",
    ],
    costPence: null,
    markupType: "none",
    markupValue: null,
    retailPricePence: null,
    providerRefs: {
      mock: "mock-sa-20gb-30d",
      airalo: "TODO_AIRALO_20GB_30D",
      maya: "TODO_MAYA_20GB_30D",
      esimaccess: "TODO_ESIMACCESS_20GB_30D",
    },
    badge: "PRICE TBD",
    active: true,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    slug: "saudi-unlimited-15-days",
    title: "Saudi Unlimited",
    subtitle: "Fair-use unlimited placeholder",
    country: "SA",
    dataAmountMb: null,
    validityDays: 15,
    network: "Zain / STC placeholder",
    description:
      "An unlimited-style Saudi data eSIM placeholder. Unlimited plans often slow down after a daily fair-use cap, so final wording must match the chosen provider.",
    featureList: [
      "Unlimited-style data placeholder",
      "15 days validity",
      "Fair-use throttling likely applies",
      "Data-only eSIM, no phone number",
    ],
    costPence: null,
    markupType: "none",
    markupValue: null,
    retailPricePence: null,
    providerRefs: {
      mock: "mock-sa-unlimited-15d",
      airalo: "TODO_AIRALO_UNLIMITED_15D",
      maya: "TODO_MAYA_UNLIMITED_15D",
      esimaccess: "TODO_ESIMACCESS_UNLIMITED_15D",
    },
    badge: "PRICE TBD",
    active: true,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
];
